# **Pandas Basics**

### **Install pandas package**

In [1]:
%pip install pandas

Requirement already satisfied: pandas in C:\Users\justin\AppData\Roaming\Python\Python314\site-packages (3.0.2)
Requirement already satisfied: numpy>=2.3.3 in c:\Users\justin\.pyenv\pyenv-win\versions\3.14.2\Lib\site-packages (from pandas) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\justin\.pyenv\pyenv-win\versions\3.14.2\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\justin\.pyenv\pyenv-win\versions\3.14.2\Lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\Users\justin\.pyenv\pyenv-win\versions\3.14.2\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution ~andas (c:\Users\justin\.pyenv\pyenv-win\versions\3.14.2\Lib\site-packages)
WARNING: Ignoring invalid distribution ~andas (c:\Users\justin\.pyenv\pyenv-win\versions\3.14.2\Lib\site-packages)
WARNING: Ignoring invalid distribution ~andas (c:\Users\justin\.pyenv\pyenv-win\versions\3.14.2\Lib\site-packages)

### **Import pandas**

In [2]:
import pandas as pd

## **DataFrames**
A DataFrame is a two-dimensional labeled data structure with columns of potentially 
different data types, similar to a spreadsheet or SQL table. 
It provides a powerful and flexible way to manipulate and analyze structured data in Python, 
offering functionalities for data analysis.

In [3]:
# .DataFrame() is a constructor function used to create new DataFrame
# Creating an Empty DataFrame
df = pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [4]:
# Create a DataFrame using a list of lists
row_data = [["John", 30], ["Jane", 28], ["Smith", 26]]
df = pd.DataFrame(row_data, columns=["Name", "Age"])
df

    Name  Age
0   John   30
1   Jane   28
2  Smith   26

In [5]:
# Create a DataFrame using a dictionary of lists
data = {
    "Name": ["John", "Jane", "Smith"],
    "Age": [30, 28, 26]
}

df = pd.DataFrame(data)
df

    Name  Age
0   John   30
1   Jane   28
2  Smith   26

In [6]:
# Create a DataFrame using a list of dictionaries
data = [
    {"Name": "John", "Age": 30},
    {"Name": "Jane", "Age": 28},
    {"Name": "Smith", "Age": 26}
]

df = pd.DataFrame(data)
df

    Name  Age
0   John   30
1   Jane   28
2  Smith   26

In [7]:
# You can use type() to check the datatype if it is Series or DataFrame
type(df)

pandas.DataFrame

## **Series**

A pandas Series is a one-dimensional labeled array capable of 
holding data of any type (integer, string, float, etc.). 
It's similar to a one-column table or an array with associated labels, 
providing powerful indexing and manipulation capabilities in Python.

In [8]:
series = pd.Series([1, 2, 3, 4, 5])
series

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [9]:
# You can use type() to check the datatype if it is Series or DataFrame
type(series)

pandas.Series

### **Pandas Data Types**

Numeric:
- Integer (int64): Represents whole numbers (e.g., 10, -5). 
    This is the default integer type in pandas. (64 bit integer)
- Float (float64): Represents numbers with decimals (e.g., 3.14, -12.5).
- Boolean (bool): Represents logical True or False values.
- Object: This is a versatile but less efficient type that can store various data types 
like strings, lists, or custom objects. 
    Pandas uses this type when it cannot infer a more specific data type.

In [10]:
# Integer (int64)
int_series = pd.Series([1, 2, 3, 4, 5])
int_series

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [11]:
# Float (float64)
float_series = pd.Series([3.14, -3.14, 0.0001, -0.0001])
float_series

0    3.1400
1   -3.1400
2    0.0001
3   -0.0001
dtype: float64

In [12]:
# Boolean (bool): (True = 1 or False = 0)
boolean_series = pd.Series([True, False, True, False])
boolean_series

0     True
1    False
2     True
3    False
dtype: bool

In [13]:
# Objects (Object / Mixed Data Types)
object_series = pd.Series([30, 3.14, True, "John"])
object_series

0      30
1    3.14
2    True
3    John
dtype: object

Specialized Data Types:
- Datetime (datetime64[ns]): Represents dates and times with nanosecond precision. 
    Useful for time-series data analysis.
- Timedelta (timedelta64[ns]): Represents durations between timestamps.
- Categorical: Represents categorical data with predefined categories. 
    Efficient for storing limited sets of categories.
- Sparse: Represents sparse data with many missing values. 
    Stores data efficiently by only keeping non-zero values.

In [14]:
# DateTime (Timestamp / datetime64)
# N: to_datetime - conver string to datetime
datetime_series = pd.Series([
    pd.to_datetime("2024-08-27 07:00:00"),
    pd.to_datetime("2024-08-27 08:30:00"),
    pd.to_datetime("2024-08-27 10:00:00"),
    pd.to_datetime("11-09-2024 05:30:00", format="%d-%m-%Y %H:%M:%S"),
    pd.to_datetime("11-2024-09 06:30:59", format="%d-%Y-%m %H:%M:%S")
])
datetime_series

0   2024-08-27 07:00:00
1   2024-08-27 08:30:00
2   2024-08-27 10:00:00
3   2024-09-11 05:30:00
4   2024-09-11 06:30:59
dtype: datetime64[us]

In [15]:
# Timedelta
timedelta_series = pd.Series([
    pd.Timedelta(days=8, hours=3, minutes=15),
    pd.Timedelta(days=4, hours=3, minutes=15),
    pd.Timedelta(days=1, hours=3, minutes=15)
])
timedelta_series

0   8 days 03:15:00
1   4 days 03:15:00
2   1 days 03:15:00
dtype: timedelta64[us]

In [16]:
# Categorical
categorical_series = pd.Series(
    pd.Categorical(["Marketing", "Sales", "Operations", "IT", "Finance", "HR"])
)
categorical_series

0     Marketing
1         Sales
2    Operations
3            IT
4       Finance
5            HR
dtype: category
Categories (6, str): ['Finance', 'HR', 'IT', 'Marketing', 'Operations', 'Sales']

In [17]:
# Sparse - missing/null values inside of the series
# N: Can include null/missing values of that datatype
sparse_series = pd.Series(
    pd.arrays.SparseArray([30, 31, 32, pd.NA, 29, 42, pd.NA])
)
sparse_series
# NaN - Not a Number

0     30
1     31
2     32
3    NaN
4     29
5     42
6    NaN
dtype: Sparse[object, nan]

### **Changing Data Types**

In [18]:
# Step 1: Check datatype
int_series.dtype

dtype('int64')

In [19]:
# Step 2: Change the datatype (float)

# astype() "as type": returns a new DataFrame where 
#           data is changed to the specified data type.

# Convert the integer to float
float_series = int_series.astype('float64')
float_series

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
dtype: float64

In [20]:
# Converting a float series to a string
string_series = float_series.astype('str')
string_series

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
dtype: str

In [21]:
# Cannot convert directly from string to int if the contents of the string contains decimal point.
# Convert to float first, then convert to int

converted_to_float = string_series.astype('float64')
converted_to_float

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
dtype: float64

In [22]:
converted_to_int = converted_to_float.astype('int64')
converted_to_int

0    1
1    2
2    3
3    4
4    5
dtype: int64

**Example: Sales Data Analysis**

You have a dataset of sales transactions that includes the product name, quantity sold, and sale price. 
You want to analyze the data to find the total revenue per product.

In [23]:
data = {
    'Product Name':['Iced Tea', 'Hot Chocolate' , 'Lemonade', 'Coffee', 'Milkshake', 'Tea', 'Smoothie', 'Soda', 'Protein Shake', 'Matcha Latte'],
    'Type': ['Cold', 'Hot', 'Cold', 'Hot', 'Cold', 'Hot', 'Cold', 'Cold', 'Cold', 'Hot'],
    'Stock': [15, 15, 15, 15, 15, 15, 15, 15, 15, 15],
    'Quantity Sold':[6, 9, 13, 11, 8, 6, 14, 10, 8, 10],
    'Manufacturing Cost':[7, 10, 6, 8, 9, 7, 10, 11, 8, 9],
    'Market Price':[13, 20, 11, 15, 19, 14, 17, 18, 20, 12],
    'Rating': [1, 3, 5, 4, 3, 2, 5, 3, 2, 3]
}

sales_df = pd.DataFrame(data)
sales_df

,Product Name,Type,Stock,Quantity Sold,Manufacturing Cost,Market Price,Rating
0,Iced Tea,Cold,15,6,7,13,1
1,Hot Chocolate,Hot,15,9,10,20,3
2,Lemonade,Cold,15,13,6,11,5
3,Coffee,Hot,15,11,8,15,4
4,Milkshake,Cold,15,8,9,19,3
5,Tea,Hot,15,6,7,14,2
6,Smoothie,Cold,15,14,10,17,5
7,Soda,Cold,15,10,11,18,3
8,Protein Shake,Cold,15,8,8,20,2
9,Matcha Latte,Hot,15,10,9,12,3

In [24]:
# Step 2: Get the Product Name column
sales_df['Product Name']

0         Iced Tea
1    Hot Chocolate
2         Lemonade
3           Coffee
4        Milkshake
5              Tea
6         Smoothie
7             Soda
8    Protein Shake
9     Matcha Latte
Name: Product Name, dtype: str

In [25]:
# Step 3: Calculate the Total Revenue
sales_df['Total Revenue'] = sales_df['Quantity Sold'] * sales_df['Market Price']
sales_df

,Product Name,Type,Stock,Quantity Sold,Manufacturing Cost,Market Price,Rating,Total Revenue
0,Iced Tea,Cold,15,6,7,13,1,78
1,Hot Chocolate,Hot,15,9,10,20,3,180
2,Lemonade,Cold,15,13,6,11,5,143
3,Coffee,Hot,15,11,8,15,4,165
4,Milkshake,Cold,15,8,9,19,3,152
5,Tea,Hot,15,6,7,14,2,84
6,Smoothie,Cold,15,14,10,17,5,238
7,Soda,Cold,15,10,11,18,3,180
8,Protein Shake,Cold,15,8,8,20,2,160
9,Matcha Latte,Hot,15,10,9,12,3,120

In [26]:
# Gross Profit: difference between total revenue and the cost of goods (Cost per product multiply to the quantity sold).
sales_df['Gross Profit'] = sales_df['Total Revenue'] - (sales_df['Quantity Sold'] * sales_df['Manufacturing Cost'])
sales_df

,Product Name,Type,Stock,Quantity Sold,Manufacturing Cost,Market Price,Rating,Total Revenue,Gross Profit
0,Iced Tea,Cold,15,6,7,13,1,78,36
1,Hot Chocolate,Hot,15,9,10,20,3,180,90
2,Lemonade,Cold,15,13,6,11,5,143,65
3,Coffee,Hot,15,11,8,15,4,165,77
4,Milkshake,Cold,15,8,9,19,3,152,80
5,Tea,Hot,15,6,7,14,2,84,42
6,Smoothie,Cold,15,14,10,17,5,238,98
7,Soda,Cold,15,10,11,18,3,180,70
8,Protein Shake,Cold,15,8,8,20,2,160,96
9,Matcha Latte,Hot,15,10,9,12,3,120,30

### **Data Selection**

Pandas provides numerous methods for selecting and indexing data in Series and DataFrames, 
including label-based indexing with .loc, integer-position based indexing with .iloc, and conditional selection.

In [27]:
sales_df

,Product Name,Type,Stock,Quantity Sold,Manufacturing Cost,Market Price,Rating,Total Revenue,Gross Profit
0,Iced Tea,Cold,15,6,7,13,1,78,36
1,Hot Chocolate,Hot,15,9,10,20,3,180,90
2,Lemonade,Cold,15,13,6,11,5,143,65
3,Coffee,Hot,15,11,8,15,4,165,77
4,Milkshake,Cold,15,8,9,19,3,152,80
5,Tea,Hot,15,6,7,14,2,84,42
6,Smoothie,Cold,15,14,10,17,5,238,98
7,Soda,Cold,15,10,11,18,3,180,70
8,Protein Shake,Cold,15,8,8,20,2,160,96
9,Matcha Latte,Hot,15,10,9,12,3,120,30

### **Data Selection in Series**

In [28]:
# [starting_index:ending_index(excluded):step]

# Getting the first two cells of the Product Name column
sales_df['Product Name'][0:2]

0         Iced Tea
1    Hot Chocolate
Name: Product Name, dtype: str

In [29]:
# Check in twos
sales_df['Product Name'][::2]

0         Iced Tea
2         Lemonade
4        Milkshake
6         Smoothie
8    Protein Shake
Name: Product Name, dtype: str

In [30]:
# OPTIONAL
# Sum of the first two rows in Quantity Sold Column
print("Sum:", sales_df['Quantity Sold'][0:2].sum())

Sum: 15

### **Data Selection in DataFrame**

#### **Index Location (.iloc)**
- Will get rows based on a number/index.
- Will output into a DataFrame instead of a Series.
> Syntax: [starting_index:ending_index(excluded):step]

In [31]:
# Note: iloc is property
sales_df

,Product Name,Type,Stock,Quantity Sold,Manufacturing Cost,Market Price,Rating,Total Revenue,Gross Profit
0,Iced Tea,Cold,15,6,7,13,1,78,36
1,Hot Chocolate,Hot,15,9,10,20,3,180,90
2,Lemonade,Cold,15,13,6,11,5,143,65
3,Coffee,Hot,15,11,8,15,4,165,77
4,Milkshake,Cold,15,8,9,19,3,152,80
5,Tea,Hot,15,6,7,14,2,84,42
6,Smoothie,Cold,15,14,10,17,5,238,98
7,Soda,Cold,15,10,11,18,3,180,70
8,Protein Shake,Cold,15,8,8,20,2,160,96
9,Matcha Latte,Hot,15,10,9,12,3,120,30

In [32]:
# [starting_index:ending_index(excluded):step]
# Getting the first three rows of the DataFrame
sales_df.iloc[:3]

,Product Name,Type,Stock,Quantity Sold,Manufacturing Cost,Market Price,Rating,Total Revenue,Gross Profit
0,Iced Tea,Cold,15,6,7,13,1,78,36
1,Hot Chocolate,Hot,15,9,10,20,3,180,90
2,Lemonade,Cold,15,13,6,11,5,143,65

In [33]:
# Without using loc, this can also work.
sales_df[0:2]

,Product Name,Type,Stock,Quantity Sold,Manufacturing Cost,Market Price,Rating,Total Revenue,Gross Profit
0,Iced Tea,Cold,15,6,7,13,1,78,36
1,Hot Chocolate,Hot,15,9,10,20,3,180,90

In [34]:
# Access rows and columns using slicing parameters
sales_df.iloc[0:3, 0:2]

    Product Name  Type
0       Iced Tea  Cold
1  Hot Chocolate   Hot
2       Lemonade  Cold

In [35]:
# Access rows and columns using list
sales_df.iloc[[0, 1], [0, 1, 2]]

    Product Name  Type  Stock
0       Iced Tea  Cold     15
1  Hot Chocolate   Hot     15

In [36]:
# Select using a value: This will return a Series
sales_df.iloc[0]

Product Name          Iced Tea
Type                      Cold
Stock                       15
Quantity Sold                6
Manufacturing Cost           7
Market Price                13
Rating                       1
Total Revenue               78
Gross Profit                36
Name: 0, dtype: object

In [37]:
# Select using a value: This will return a Series
sales_df.iloc[1]

Product Name          Hot Chocolate
Type                            Hot
Stock                            15
Quantity Sold                     9
Manufacturing Cost               10
Market Price                     20
Rating                            3
Total Revenue                   180
Gross Profit                     90
Name: 1, dtype: object

#### **Location (.loc)**
- Access a group of rows and columns by label(s) or a boolean array.
> Syntax: [starting_index:ending_index(included):step]

In [38]:
sales_df

,Product Name,Type,Stock,Quantity Sold,Manufacturing Cost,Market Price,Rating,Total Revenue,Gross Profit
0,Iced Tea,Cold,15,6,7,13,1,78,36
1,Hot Chocolate,Hot,15,9,10,20,3,180,90
2,Lemonade,Cold,15,13,6,11,5,143,65
3,Coffee,Hot,15,11,8,15,4,165,77
4,Milkshake,Cold,15,8,9,19,3,152,80
5,Tea,Hot,15,6,7,14,2,84,42
6,Smoothie,Cold,15,14,10,17,5,238,98
7,Soda,Cold,15,10,11,18,3,180,70
8,Protein Shake,Cold,15,8,8,20,2,160,96
9,Matcha Latte,Hot,15,10,9,12,3,120,30

In [39]:
# [start:end(included):step]
sales_df.loc[1:5, "Product Name":"Market Price"]

    Product Name  Type  Stock  Quantity Sold  Manufacturing Cost  Market Price
1  Hot Chocolate   Hot     15              9                  10            20
2       Lemonade  Cold     15             13                   6            11
3         Coffee   Hot     15             11                   8            15
4      Milkshake  Cold     15              8                   9            19
5            Tea   Hot     15              6                   7            14

In [40]:
# Get the first three rows/records and get the custom list of columns
sales_df.loc[:2, ["Product Name", "Quantity Sold", "Market Price", "Total Revenue"]]

    Product Name  Quantity Sold  Market Price  Total Revenue
0       Iced Tea              6            13             78
1  Hot Chocolate              9            20            180
2       Lemonade             13            11            143

## **Conditional Filtering**

In [41]:
# Check if a field satisfies the condition
sales_df["Total Revenue"] >= 150

0    False
1     True
2    False
3     True
4     True
5    False
6     True
7     True
8     True
9    False
Name: Total Revenue, dtype: bool

In [42]:
# Get all products that have total revenue greater than or equal 150
sales_df[sales_df["Total Revenue"] >= 150]

,Product Name,Type,Stock,Quantity Sold,Manufacturing Cost,Market Price,Rating,Total Revenue,Gross Profit
1,Hot Chocolate,Hot,15,9,10,20,3,180,90
3,Coffee,Hot,15,11,8,15,4,165,77
4,Milkshake,Cold,15,8,9,19,3,152,80
6,Smoothie,Cold,15,14,10,17,5,238,98
7,Soda,Cold,15,10,11,18,3,180,70
8,Protein Shake,Cold,15,8,8,20,2,160,96

In [43]:
# Task: Get all cold beverages that have a total revenue greater than or equal to 150
sales_df[(sales_df["Type"] == "Cold") & (sales_df["Total Revenue"] >= 150)]

,Product Name,Type,Stock,Quantity Sold,Manufacturing Cost,Market Price,Rating,Total Revenue,Gross Profit
4,Milkshake,Cold,15,8,9,19,3,152,80
6,Smoothie,Cold,15,14,10,17,5,238,98
7,Soda,Cold,15,10,11,18,3,180,70
8,Protein Shake,Cold,15,8,8,20,2,160,96

In [44]:
# Using querry() for indexing/filtering
# N: Backticks(``) - Columns (Can be used for complex querying)
# N: Double Quotes ("") - String values
high_rating = sales_df.query("`Rating` >= 3")
high_rating

,Product Name,Type,Stock,Quantity Sold,Manufacturing Cost,Market Price,Rating,Total Revenue,Gross Profit
1,Hot Chocolate,Hot,15,9,10,20,3,180,90
2,Lemonade,Cold,15,13,6,11,5,143,65
3,Coffee,Hot,15,11,8,15,4,165,77
4,Milkshake,Cold,15,8,9,19,3,152,80
6,Smoothie,Cold,15,14,10,17,5,238,98
7,Soda,Cold,15,10,11,18,3,180,70
9,Matcha Latte,Hot,15,10,9,12,3,120,30

In [45]:
sales_for_cold_beverages = sales_df.query("Type == 'Cold' and `Total Revenue` >= 150")
sales_for_cold_beverages

,Product Name,Type,Stock,Quantity Sold,Manufacturing Cost,Market Price,Rating,Total Revenue,Gross Profit
4,Milkshake,Cold,15,8,9,19,3,152,80
6,Smoothie,Cold,15,14,10,17,5,238,98
7,Soda,Cold,15,10,11,18,3,180,70
8,Protein Shake,Cold,15,8,8,20,2,160,96

## **Apply**

The apply function in pandas is a powerful tool for working with DataFrames. 
It allows you to apply a custom function to each element (row or column) of the DataFrame 
and return a new DataFrame or Series based on the results.

In [46]:
sales_df

,Product Name,Type,Stock,Quantity Sold,Manufacturing Cost,Market Price,Rating,Total Revenue,Gross Profit
0,Iced Tea,Cold,15,6,7,13,1,78,36
1,Hot Chocolate,Hot,15,9,10,20,3,180,90
2,Lemonade,Cold,15,13,6,11,5,143,65
3,Coffee,Hot,15,11,8,15,4,165,77
4,Milkshake,Cold,15,8,9,19,3,152,80
5,Tea,Hot,15,6,7,14,2,84,42
6,Smoothie,Cold,15,14,10,17,5,238,98
7,Soda,Cold,15,10,11,18,3,180,70
8,Protein Shake,Cold,15,8,8,20,2,160,96
9,Matcha Latte,Hot,15,10,9,12,3,120,30

In [47]:
def discount(original_price):
    discount_rate = 0.10
    discount_amount = original_price  * discount_rate
    discounted_price = original_price - discount_amount
    return discounted_price

sales_df["10% Discounted Price"] = sales_df["Market Price"].apply(discount)
sales_df

,Product Name,Type,Stock,Quantity Sold,Manufacturing Cost,Market Price,Rating,Total Revenue,Gross Profit,10% Discounted Price
0,Iced Tea,Cold,15,6,7,13,1,78,36,11.7
1,Hot Chocolate,Hot,15,9,10,20,3,180,90,18.0
2,Lemonade,Cold,15,13,6,11,5,143,65,9.9
3,Coffee,Hot,15,11,8,15,4,165,77,13.5
4,Milkshake,Cold,15,8,9,19,3,152,80,17.1
5,Tea,Hot,15,6,7,14,2,84,42,12.6
6,Smoothie,Cold,15,14,10,17,5,238,98,15.3
7,Soda,Cold,15,10,11,18,3,180,70,16.2
8,Protein Shake,Cold,15,8,8,20,2,160,96,18.0
9,Matcha Latte,Hot,15,10,9,12,3,120,30,10.8

In [48]:
# Get the items with total revenue >= 150
def best_sellers(total_revenue):
    return total_revenue >= 150

df_best_sellers = sales_df[sales_df["Total Revenue"].apply(best_sellers)]
df_best_sellers

,Product Name,Type,Stock,Quantity Sold,Manufacturing Cost,Market Price,Rating,Total Revenue,Gross Profit,10% Discounted Price
1,Hot Chocolate,Hot,15,9,10,20,3,180,90,18.0
3,Coffee,Hot,15,11,8,15,4,165,77,13.5
4,Milkshake,Cold,15,8,9,19,3,152,80,17.1
6,Smoothie,Cold,15,14,10,17,5,238,98,15.3
7,Soda,Cold,15,10,11,18,3,180,70,16.2
8,Protein Shake,Cold,15,8,8,20,2,160,96,18.0

## Pandas Operators
Data Analysis:

- sum(): Calculates the sum of a Series or DataFrame
- mean(): Calculates the mean of a Series or DataFrame
- median(): Calculates the median of a Series or DataFrame
- std(): Calculates the standard deviation of a Series or DataFrame
- var(): Calculates the variance of a Series or DataFrame

Data Loading and Exploration:

- head(): Shows the first few rows of a DataFrame
- tail(): Shows the last few rows of a DataFrame
- info(): Displays information about the DataFrame, including data types and memory usage
- describe(): Generates summary statistics for each column (mean, standard deviation, etc.)

In [49]:
print("Sum of Rating Column:", sales_df["Total Revenue"].sum())

Sum of Rating Column: 1500

In [50]:
# Steps to get the mean/average
# 1. Add all the data.
# 2. Divide the data by how many data we have.
print("Mean/Average of Rating Column:", sales_df["Rating"].mean())

Mean/Average of Rating Column: 3.1

In [51]:
# Steps to get the median
# 1. Sort the values
# 2. 2 Possible Options
#      1. Odd - You can get the middle value.
#      2. Even - Add the middle two and divide by 2.
rating_list = sales_df["Rating"].tolist() # reverse=True , descending order
rating_list.sort()
print(rating_list)

[1, 2, 2, 3, 3, 3, 3, 4, 5, 5]

In [52]:
print("Media of Rating Column:", sales_df["Rating"].median())

Media of Rating Column: 3.0

In [53]:
# You can use this to sort the values.
sales_df["Rating"].sort_values()

0    1
5    2
8    2
4    3
7    3
1    3
9    3
3    4
6    5
2    5
Name: Rating, dtype: int64

In [54]:
# Deviation: Distance of a unit from the mean.
# Standard Deviation: how far apart the values are from their mean (average).
# Data Analysis: Used to describe the distribution of data and identify outliers.
# LOW - Data is close to the mean. 
# HIGH - Data is distributed/spread out from the mean. (Presence of outliers.)
# Zero - All data points are identical.

print("Standard Deviation of Rating Column:", sales_df["Rating"].std().round(2))

# Outliers are data points that significantly deviate from the majority of the data in a dataset. 
# They can be either unusually high or unusually low compared to the rest of the data.

# .round(no_of_decimal_places): round your number to the nearest decimal point.

Standard Deviation of Rating Column: 1.29

In [55]:
# Variance: how far apart the values are from their mean (average).
# LOW - Data is close to the mean. 
# HIGH - Data is distributed/spread out from the mean. (Presence of outliers.)
# Zero - All data points are identical.

print("Variance of Rating Column", sales_df["Rating"].var().round(2))

# Difference between Standard Deviation and Variance
# Units: Variance is expressed in squared units of the original data, 
# while standard deviation is expressed in the same units as the original.

Variance of Rating Column 1.66

In [56]:
# head(num_row) 5 by default
sales_df.head()
sales_df.head(3)

,Product Name,Type,Stock,Quantity Sold,Manufacturing Cost,Market Price,Rating,Total Revenue,Gross Profit,10% Discounted Price
0,Iced Tea,Cold,15,6,7,13,1,78,36,11.7
1,Hot Chocolate,Hot,15,9,10,20,3,180,90,18.0
2,Lemonade,Cold,15,13,6,11,5,143,65,9.9

In [57]:
# tail(num_row) 5 by default
sales_df.tail()
sales_df.tail(3)

,Product Name,Type,Stock,Quantity Sold,Manufacturing Cost,Market Price,Rating,Total Revenue,Gross Profit,10% Discounted Price
7,Soda,Cold,15,10,11,18,3,180,70,16.2
8,Protein Shake,Cold,15,8,8,20,2,160,96,18.0
9,Matcha Latte,Hot,15,10,9,12,3,120,30,10.8

In [58]:
# info() - information of the table
sales_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Product Name          10 non-null     str
 1   Type                  10 non-null     str
 2   Stock                 10 non-null     int64
 3   Quantity Sold         10 non-null     int64
 4   Manufacturing Cost    10 non-null     int64
 5   Market Price          10 non-null     int64
 6   Rating                10 non-null     int64
 7   Total Revenue         10 non-null     int64
 8   Gross Profit          10 non-null     int64
 9   10% Discounted Price  10 non-null     float64
dtypes: float64(1), int64(7), str(2)
memory usage: 932.0 bytes

In [59]:
# describe() - count, mean, std, min, 25%, 50%, 75%, max
# N: count: number of values
# N: mean: average
# N: standard deviation: how far apart the values are from their mean (average).
# LOW - Data is close to the mean. 
# HIGH - Data is distributed/spread out from the mean.
# Zero - All data points are identical.
# N: min: lowest value
# N: 25%: value in the 25th percentile
# N: 50%: median: value in the middle
# N: 75%: value in the 75th percentile
# N: max: maximum value
sales_df.describe()

,Stock,Quantity Sold,Manufacturing Cost,Market Price,Rating,Total Revenue,Gross Profit,10% Discounted Price
count,10.0,10.000000,10.000000,10.0000,10.000000,10.00000,10.000000,10.00000
mean,15.0,9.500000,8.500000,15.9000,3.100000,150.00000,68.400000,14.31000
std,0.0,2.677063,1.581139,3.3483,1.286684,47.56516,24.829194,3.01347
min,15.0,6.000000,6.000000,11.0000,1.000000,78.00000,30.000000,9.90000
25%,15.0,8.000000,7.250000,13.2500,2.250000,125.75000,47.750000,11.92500
50%,15.0,9.500000,8.500000,16.0000,3.000000,156.00000,73.500000,14.40000
75%,15.0,10.750000,9.750000,18.7500,3.750000,176.25000,87.500000,16.87500
max,15.0,14.000000,11.000000,20.0000,5.000000,238.00000,98.000000,18.00000

### **Aggregating Data** (.groupby)

Aggregating data involves summarizing data points into meaningful statistics, 
such as averages, sums, or counts, which can be achieved using GroupBy operations or pivot tables. 
This helps in understanding the dataset at a higher level.

In [60]:
# Step 1: Get the unique values from the Type column.
sales_df["Type"].unique()

<StringArray>
['Cold', 'Hot']
Length: 2, dtype: str

In [61]:
# Step 2: Changing data type to category
sales_df["Type"] = sales_df["Type"].astype("category")

In [62]:
# Step 3: Check the data type
sales_df["Type"].dtype

CategoricalDtype(categories=['Cold', 'Hot'], ordered=False, categories_dtype=str)

In [63]:
sales_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Product Name          10 non-null     str
 1   Type                  10 non-null     category
 2   Stock                 10 non-null     int64
 3   Quantity Sold         10 non-null     int64
 4   Manufacturing Cost    10 non-null     int64
 5   Market Price          10 non-null     int64
 6   Rating                10 non-null     int64
 7   Total Revenue         10 non-null     int64
 8   Gross Profit          10 non-null     int64
 9   10% Discounted Price  10 non-null     float64
dtypes: category(1), float64(1), int64(7), str(1)
memory usage: 878.0 bytes

In [64]:
# Step 4
# Task: Get the total revenue of all the cold beverages combined and all the hot beverages combined.
total_revenue_based_on_type = sales_df.groupby('Type')['Total Revenue'].sum()
total_revenue_based_on_type

Type
Cold    951
Hot     549
Name: Total Revenue, dtype: int64

In [65]:
# Step 5: Add the data inside the DataFrame
total_revenue_based_on_type_df = pd.DataFrame()
total_revenue_based_on_type_df['Total Revenue'] = sales_df.groupby('Type')['Total Revenue'].sum()
total_revenue_based_on_type_df

      Total Revenue
Type
Cold            951
Hot             549

In [66]:
# Step 6: Create a new column
total_revenue_based_on_type_df['Quantity Sold'] = sales_df.groupby('Type')['Quantity Sold'].sum()
total_revenue_based_on_type_df

      Total Revenue  Quantity Sold
Type
Cold            951             59
Hot             549             36